server.port=3000
management.influx.metrics.export.uri = http://influxdb:8086
management.influx.metrics.export.org = org
management.influx.metrics.export.bucket = bucket
management.influx.metrics.export.token = bzO10KmR8x
management.influx.metrics.export.api-version = v2
management.influx.metrics.export.step = 1s