services:
  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=dapr
      - DOCKER_INFLUXDB_INIT_BUCKET=bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=auth
    networks:
      - influx-net

  redis:
    image: redis:6
    networks:
      - dining-philosophers

  actor-service-0:
    build:
      context: ..
      dockerfile: ./DiningPhilosophers/Dockerfile
    image: dining-philosophers-dapr:latest
    environment:
      - TYPE=SERVICE
      - HOST_ARBITRATOR_ACTOR=true
      - HOST_PHILOSOPHER_PUBSUB=true
      - NUMBER_OF_PHILOSOPHERS=6
      - HOSTED_PHILOSOPHERS=0-2
      - PHILOSOPHER_EATING_ROUNDS=16000
      - PHILOSOPHER_EATING_TIME_MS=0
      - DAPR_HTTP_ENDPOINT=http://actor-service-0-sidecar:3500
      - DAPR_GRPC_ENDPOINT=http://actor-service-0-sidecar:50001
    networks:
      - cluster0
      - influx-net


  actor-service-0-sidecar:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "philosopher-service-sidecar-0",
      "--app-channel-address", "actor-service-0",
      "--app-port", "3000",
      "--resources-path", "/components",
      "--placement-host-address", "placement0:50006",
    ]
    volumes:
      - "./components:/components"
    networks:
      - cluster0
      - dining-philosophers

  actor-service-1:
    build:
      context: ..
      dockerfile: ./DiningPhilosophers/Dockerfile
    image: dining-philosophers-dapr:latest
    environment:
      - TYPE=SERVICE
      - HOST_PHILOSOPHER_PUBSUB=true
      - NUMBER_OF_PHILOSOPHERS=6
      - HOSTED_PHILOSOPHERS=3-5
      - PHILOSOPHER_EATING_ROUNDS=16000
      - PHILOSOPHER_EATING_TIME_MS=0
      - DAPR_HTTP_ENDPOINT=http://actor-service-1-sidecar:3500
      - DAPR_GRPC_ENDPOINT=http://actor-service-1-sidecar:50001
    networks:
      - cluster1
      - influx-net

  actor-service-1-sidecar:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "philosopher-service-sidecar-1",
      "--app-channel-address", "actor-service-1",
      "--app-port", "3000",
      "--resources-path", "/components",
      "--placement-host-address", "placement1:50006",
    ]
    volumes:
      - "./components:/components"
    networks:
      - cluster1
      - dining-philosophers

  actor-client:
    image: dining-philosophers-dapr:latest
    pull_policy: never
    environment:
      - TYPE=CLIENT
      - DAPR_HTTP_ENDPOINT=http://actor-client-sidecar:3500
      - DAPR_GRPC_ENDPOINT=http://actor-client-sidecar:50001
    networks:
      - client
    depends_on:
      - actor-service-0
      - actor-service-1

  actor-client-sidecar:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "philosopher-client",
      "--app-channel-address", "actor-client",
      "--app-port", "3000",
      "--resources-path", "/components",
    ]
    volumes:
      - "./components:/components"
    networks:
      - client
      - dining-philosophers

  placement0:
    image: "daprio/placement:edge"
    command: ["./placement", "--port", "50006"]
    networks:
      - cluster0

  placement1:
    image: "daprio/placement:edge"
    command: [ "./placement", "--port", "50006" ]
    networks:
      - cluster1

networks:
  dining-philosophers:
  cluster0:
  cluster1:
  client:
  influx-net: