services:
  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=dapr
      - DOCKER_INFLUXDB_INIT_BUCKET=bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=auth

  redis:
    image: redis:8.2.4-alpine

  placement:
    image: "daprio/placement:edge"
    command: [ "./placement", "--port", "50006" ]

  arbitrator:
    build: .
    environment:
      - ROLE=arbitrator
      - NUMBER_OF_PHILOSOPHERS=6
      - DAPR_HTTP_ENDPOINT=http://arbitrator-sidecar:3500
      - DAPR_GRPC_ENDPOINT=http://arbitrator-sidecar:50001
    depends_on:
      - arbitrator-sidecar

  arbitrator-sidecar:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "arbitrator-sidecar",
      "--app-channel-address", "arbitrator",
      "--app-port", "3000",
      "--resources-path", "/components",
      "--placement-host-address", "placement:50006",
    ]
    volumes:
      - "./redis/components:/components"
    depends_on:
      - redis

  w0:
    build: .
    environment:
      - PHILOSOPHER_ID=0
      - DAPR_HTTP_ENDPOINT=http://w0-sidecar:3500
      - DAPR_GRPC_ENDPOINT=http://w0-sidecar:50001
    depends_on:
      - w0-sidecar

  w0-sidecar:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "w0-sidecar",
      "--app-channel-address", "w0",
      "--app-port", "3000",
      "--resources-path", "/components",
      "--placement-host-address", "placement:50006",
    ]
    volumes:
      - "./redis/components:/components"
    depends_on:
      - redis

  w1:
    build: .
    environment:
      - PHILOSOPHER_ID=1
      - DAPR_HTTP_ENDPOINT=http://w1-sidecar:3500
      - DAPR_GRPC_ENDPOINT=http://w1-sidecar:50001
    depends_on:
      - w1-sidecar

  w1-sidecar:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "w1-sidecar",
      "--app-channel-address", "w1",
      "--app-port", "3000",
      "--resources-path", "/components",
      "--placement-host-address", "placement:50006",
    ]
    volumes:
      - "./redis/components:/components"
    depends_on:
      - redis

  w2:
    build: .
    environment:
      - PHILOSOPHER_ID=2
      - DAPR_HTTP_ENDPOINT=http://w2-sidecar:3500
      - DAPR_GRPC_ENDPOINT=http://w2-sidecar:50001
    depends_on:
      - w2-sidecar

  w2-sidecar:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "w2-sidecar",
      "--app-channel-address", "w2",
      "--app-port", "3000",
      "--resources-path", "/components",
      "--placement-host-address", "placement:50006",
    ]
    volumes:
      - "./redis/components:/components"
    depends_on:
      - redis

  w3:
    build: .
    environment:
      - PHILOSOPHER_ID=3
      - DAPR_HTTP_ENDPOINT=http://w3-sidecar:3500
      - DAPR_GRPC_ENDPOINT=http://w3-sidecar:50001
    depends_on:
      - w3-sidecar

  w3-sidecar:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "w3-sidecar",
      "--app-channel-address", "w3",
      "--app-port", "3000",
      "--resources-path", "/components",
      "--placement-host-address", "placement:50006",
    ]
    volumes:
      - "./redis/components:/components"
    depends_on:
      - redis

  w4:
    build: .
    environment:
      - PHILOSOPHER_ID=4
      - DAPR_HTTP_ENDPOINT=http://w4-sidecar:3500
      - DAPR_GRPC_ENDPOINT=http://w4-sidecar:50001
    depends_on:
      - w4-sidecar

  w4-sidecar:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "w4-sidecar",
      "--app-channel-address", "w4",
      "--app-port", "3000",
      "--resources-path", "/components",
      "--placement-host-address", "placement:50006",
    ]
    volumes:
      - "./redis/components:/components"
    depends_on:
      - redis

  w5:
    build: .
    environment:
      - PHILOSOPHER_ID=5
      - DAPR_HTTP_ENDPOINT=http://w5-sidecar:3500
      - DAPR_GRPC_ENDPOINT=http://w5-sidecar:50001
    depends_on:
      - w5-sidecar

  w5-sidecar:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "w5-sidecar",
      "--app-channel-address", "w5",
      "--app-port", "3000",
      "--resources-path", "/components",
      "--placement-host-address", "placement:50006",
    ]
    volumes:
      - "./redis/components:/components"
    depends_on:
      - redis